             <form class="login" method="post" action="?">
                <input type="text" name="username" class="textinput" placeholder="Username" required autofocus style="width: 210px";>
                    <br>
                <input type="password" name="password" class="textinput" placeholder="Password" required style="width: 210px";>
                    <br>
                <input type="submit" name="Log In" value="Log In" id="loginbutton" style="width: 210px";>

            </form>
             